stages:
  # - code-quality
  - testing
jobs:
  include:
    - language: generic
      env: NAME="PHP tests"
      stage: testing
      sudo: required
      services:
        - docker
      cache:
        directories:
          - $HOME/.composer
      before_script:
        - ./develop.sh up -d db-test
        - ./develop.sh build php
        - ./develop.sh run --rm php composer install
        - ./develop.sh run --rm php php artisan migrate --force --database=test --seed
      script:
        - ./develop.sh run --rm php ./vendor/bin/phpunit
