version: "3"

services:
  db:
    image: mysql:8.0.19
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    volumes:
      - db_database:/var/lib/mysql

  db-test:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - db_test_database:/var/lib/mysql

  php:
    build:
      context: ./api
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./api:/var/www/html
      - ~/.composer:/root/.composer

  ngnix:
    image: nginx:alpine
    volumes:
      - ./api:/var/www/html
      - ./front/nginx/www.conf:/etc/nginx/conf.d/default.conf
      - ./front/docs:/var/www/html/docs
      - ./front/node_modules/redoc/bundles:/var/www/html/docs/redoc/bundles
    working_dir: /var/www/html
    ports:
      - 80:80

  redis:
    image: redis:6.0-rc-alpine
    command: --requirepass $REDIS_PASSWORD

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 81:8080
volumes:
  db_database:
  db_test_database:
